---
# - name: Install Vector
#   hosts: vector-01
#   become: true
#   # handlers:
#   tasks:
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.49.0/vector-0.49.0-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "0644"
    owner: ansible-user
- name: Install vector packages
  ansible.builtin.package:
    name:
      - vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: true
- name: Create Vector config directory
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: "0755"
    owner: ansible-user
- name: Deploy Vector config
  ansible.builtin.template:
    src: ./templates/vector.yml.j2
    dest: "{{ vector_config_path }}"
    mode: "0644"
    owner: ansible-user
    validate: vector validate --no-environment --config-yaml %s
  notify: Restart vector service
- name: Ensure Vector is running
  ansible.builtin.service:
    name: vector
    state: started
    enabled: true

