---
- name: Install package based on OS
  become: true
  block:
    - name: Gather OS facts
      ansible.builtin.setup:

    - name: Debug OS Family
      debug:
        var: ansible_os_family 

    - name: OS Family
      debug:
        msg: "{{ ansible_os_family }}"

    - name: Download RPM package
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version_rpm }}/vector-{{ vector_version_rpm }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version_rpm }}-1.x86_64.rpm"
        mode: "0644"
      when: ansible_os_family in ['CentOS', 'RedHat', 'Fedora']

    - name: Download DEB package
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version_deb }}/vector_{{ vector_version_deb }}-1_amd64.deb"
        dest: "./vector-{{ vector_version_deb }}-1.amd64.deb"
        mode: "0644"
      when: ansible_os_family in ['Ubuntu', 'Debian']

    - name: Install on RHEL-based systems
      yum:
        name: "./vector-{{ vector_version_rpm }}-1.x86_64.rpm"
        state: present
        disable_gpg_check: true
      when: ansible_distribution in ['CentOS', 'RedHat', 'Fedora', 'Rocky']

    - name: Install on Debian-based systems
      apt:
        deb: "./vector-{{ vector_version_deb }}-1.amd64.deb"
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Create Vector config directory
  become: true
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: "0755"
- name: Deploy Vector config
  become: true
  ansible.builtin.template:
    src: ./templates/vector.yml.j2
    dest: "{{ vector_config_path }}"
    mode: "0644"
    validate: vector validate --no-environment --config-yaml %s
#   notify: Restart vector service
# - name: Ensure Vector is running
#   become: true
#   ansible.builtin.service:
#     name: vector
#     state: started
#     enabled: true