---
dependency:
  name: galaxy
driver:
  name: podman #docker

platforms:
  - name: fedora_latest
    image: docker.io/pycontribs/fedora
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
  scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy