---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      include_role:
        name: /home/aleksandrov_sp/netology/dz_ansible/netology_homework_ansible/dz_05_ansible/roles/vector-role
