---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      include_role:
        name: /home/aleksandrov_sp/netology/other/dz_04_ansible/vector-role
